#!/bin/bash
# Description: Runs prettier before committing files.
# src: https://prettier.io/docs/en/precommit.html

echo "Pre commit hook: Running prettier on changed files and adding them to
staging.."

FILES=$(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g')
[ -z "$FILES" ] && exit 0

# Prettify all selected files
echo "$FILES" | xargs ./node_modules/.bin/prettier --ignore-unknown --write

# Add back the modified/prettified files to staging
echo "$FILES" | xargs git add

echo "Prettier run done!"
exit 0


